inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  Exclude:
    - db/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - bin/**/*
    - config/environments/*
    - config/initializers/*
  DisplayCopNames: true
  TargetRailsVersion: 6.0

Rails:
  Enabled: true

Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
